import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { to, title, message, shareUrl } = await req.json();

    if (!to) {
      return NextResponse.json(
        { error: "Recipient email is required" },
        { status: 400 }
      );
    }

    const resendApiKey = process.env.RESEND_API_KEY;

    if (!resendApiKey) {
      return NextResponse.json(
        { error: "RESEND_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const { Resend } = await import("resend");

    const resend = new Resend(resendApiKey);

    const { data, error } = await resend.emails.send({
      from: "DOCUVAT <noreply@docuvat.com>",
      to: [to],
      subject: title || "Document from DOCUVAT",
      html: `
        <div style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;padding:32px;">
          <h2 style="margin:0 0 12px;">${title || "DOCUVAT Document"}</h2>
          <p style="color:#475569;line-height:1.7;">
            ${message || "Please review the shared document."}
          </p>

          ${
            shareUrl
              ? `<p style="margin-top:24px;">
                  <a href="${shareUrl}" style="background:#2563eb;color:white;padding:12px 18px;border-radius:10px;text-decoration:none;display:inline-block;">
                    Open Document
                  </a>
                </p>`
              : ""
          }

          <p style="color:#94a3b8;font-size:12px;margin-top:32px;">
            Generated by DOCUVAT
          </p>
        </div>
      `,
    });

    if (error) {
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({
      success: true,
      data,
    });
  } catch (error) {
    console.error(error);

    return NextResponse.json(
      { error: "Failed to send document" },
      { status: 500 }
    );
  }
}